name: Astrocadre CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout the master branch
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install the dependencies
      run: npm install

    - name: Execute the tests
      run: npm run test-headless

    - name: Execute the production build
      run: npm run build:prod

    - name: Checkout the gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        clean: false

    - name: Update the GitHub pages of the project
      run: |
          rm -rf ./docs
          mv ./dist ./docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A -f ./docs
          git commit -m 'Update GitHub pages'
          git push
