name: Astrocadre CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install the dependencies
      run: npm install

    - name: Execute the tests
      run: npm run test-headless

    - name: Execute the production build
      run: npm run build:prod

    - name: Copy the dist into GitHub pages of the project
      run: git checkout gh-pages
      run: rm -rf ./docs && mv ./dist ./docs
      run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Web Flow"
          git add -A
          git commit -m 'Update GitHub pages'
          git push
